[package]
name = "hyperon-common"
version.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }
itertools = "0.13.0"
bimap = "0.6.3"

[lib]
path = "src/lib.rs"
crate-type = ["lib"]
